services:
  node:
    image: node:26-alpine
    working_dir: /app
    command: node --watch index.ts
    ports:
      - '9090:3000'
    volumes:
      - .:/app
      - database:/database
      - files:/files
  caddy:
    image: caddy:alpine
    ports:
      - '80:80'
    volumes:
      - ./front:/usr/share/caddy

volumes:
  database:
  files: